// components/utils.js
export const translations = {
  en: {
    welcomeMessage: "Welcome to Zero Bookmark Manager Chat!",
    welcomeSubMessage: "How can I assist you today?",
    startButton: "Start Chat",
    allBookmarks: "All Bookmarks",
    sortDefault: "Sort: Default",
    sortNew: "New to Old",
    sortOld: "Old to New",
    sortLastOpened: "By Last Opened",
    sortAZ: "A to Z",
    sortZA: "Z to A",
    sortFavorites: "Favorites",
    sortMostVisited: "Most Visited",
    sortDomain: "By Domain",
    createFolder: "Create Folder",
    addToFolder: "Add to Folder",
    deleteFolder: "Delete Folder",
    settings: "Settings",
    exportBookmarks: "Export Bookmarks",
    importBookmarks: "Import Bookmarks",
    selectAll: "Select All",
    showCheckboxes: "Show Checkboxes",
    hideCheckboxes: "Hide Checkboxes",
    searchPlaceholder: "Search bookmarks...",
    renameTitle: "Rename",
    renameFolder: "Rename Folder",
    renamePlaceholder: "Enter new name...",
    addToFolderTitle: "Add to Folder",
    selectFolder: "Select Folder",
    newFolderPlaceholder: "Name folder want to add",
    createNewFolder: "Create",
    save: "Save",
    cancel: "Cancel",
    totalBookmarks: "Total Bookmarks",
    scrollToTop: "Scroll to Top",
    clear: "Clear",
    deleteConfirm: "Are you sure you want to delete this bookmark?",
    deleteFolderConfirm:
      "Are you sure you want to delete this folder? Bookmarks that exist in other folders will be preserved.",
    confirmDeleteTag:
      "Are you sure you want to delete this tag from the bookmark?",
    deleteTagSuccess: "Tag deleted successfully!",
    discardFolderPrompt:
      "You entered a folder name but didn't save. Discard it?",
    noBookmarks: "No bookmarks found. Please check permissions.",
    emptyTitleError: "Title cannot be empty",
    emptyFolderError: "Folder name cannot be empty",
    selectFolderError: "Select a folder or create a new one",
    errorUnexpected: "Unexpected error occurred. Please try again.",
    clearRenameAria: "Clear rename input",
    clearSearchAria: "Clear search input",
    settingsButtonAria: "Open settings menu",
    addToFolderOption: "Add to Folder",
    deleteBookmarkOption: "Delete",
    renameBookmarkOption: "Rename",
    editInNewTabOption: "Open Web View",
    openSidePanel: "Open Side Panel",
    deleteBookmarks: "Delete bookmark",
    importSuccess: "Bookmarks imported successfully!",
    importDuplicatePrompt:
      "Some bookmarks already exist (same URL). Do you want to import the non-duplicate bookmarks?",
    importInvalidFile:
      "Invalid file format. Please select a valid JSON bookmark file.",
    importError: "Failed to import bookmarks. Please try again.",
    deleteBookmarkSuccess: "Bookmark deleted successfully!",
    exportPrompt:
      "Choose export format: JSON or HTML (data will be saved as JSON).",
    createFolderSuccess: "Folder created successfully!",
    confirmTitle: "Confirm",
    successTitle: "Success",
    errorTitle: "Error",
    renameSuccess: "Bookmark renamed successfully!",
    addToFolderSuccess:
      "Bookmark(s) added to folder successfully! (Reload to update data)",
    createFolderSuccess: "Folder created successfully!",
    duplicateTitleError: "Title already exists in this folder",
    emptyTitleError: "Please enter a title",
    emptyFolderError: "Please enter a folder name or select a folder",
    noBookmarksSelected: "No bookmarks selected",
    selectFolderError: "Please select a folder",
    errorUnexpected: "An unexpected error occurred",
    restartExtension: "Please try again or restart the extension.",
    renamePlaceholder: "Enter new bookmark name",
    newFolderPlaceholder: "Enter folder name",
    selectFolder: "Select Folder",
    exportTitle: "Export Bookmarks",
    advancedSettings: "Advanced Settings (HTML & CSV)",
    includeCreationDates: "Include creation dates",
    includeFolderModDates: "Include folder modification dates",
    popupSubtitle: "Choose your preferred export format and settings",
    exportFormat: "Export Format",
    jsonDescription: "Machine readable format (backup and restore with import)",
    htmlDescription: "Interactive web page",
    csvDescription: "Tabular data (easily open in Excel/Sheets)",
    netscapeDescription: "Standard browser format",
    includeCreationDatesDescription: "Add creation timestamps",
    includeFolderModDatesDescription: "Add folder timestamps",
    exporting: "Exporting...",
    bookmarksTitle: "My Bookmarks Collection",
    bookmarksHeader: "My Bookmarks",
    exportedOn: "Exported on",
    loadingBookmarks: "Loading bookmarks...",
    generatedBy: "Generated by Zero Bookmark Manager Extension",
    bookmarks: "bookmarks",
    folders: "folders",
    created: "Created",
    modified: "Modified",
    unnamedFolder: "Unnamed Folder",
    notAvailable: "N/A",
    scrollToTop: "Scroll to Top",
    aiTitle: "Configure AI Chatbot",
    favourite: "Favourite",
    removeFavourite: "Remove from Favorites",
    favoriteSuccess: "Bookmark added to favorites!",
    unfavoriteSuccess: "Bookmark removed from favorites!",
    helpGuideTitle: "Help Guide",
    exportChatHistory: "Export Chat History",
    maximizeMinimize: "Maximize/Minimize",
    editAIConfig: "Edit AI Config",
    closeChat: "Close Chat",
    chatToggle: "Open Chat",
    noChatHistory: "No chat history available",
    loadingChat: "Processing...",
    moveBookmarkSuccess: "Bookmark moved successfully",
    moveBookmarkError: "Bookmark not found or invalid folder",
    searchFolderResult: "Found folders",
    noFoldersFound: "No folders found for",
    aiBookmarkResponse: "AI Response",
    notSupported:
      "Sorry, I can only help with bookmark-related tasks or simple questions like the time or day.",
    youHave: "You have",
    hereAreYourBookmarks: "Here are your bookmarks",
    hereAreYourFolders: "Here are your folders",
    hereAreBookmarksInFolder: "Here are the bookmarks in folder",
    noBookmarksInFolder: "No bookmarks in this folder",
    addedBookmarkToFolder: "I've added the bookmark",
    toFolder: "to the folder",
    updatedBookmark: "I've updated the bookmark",
    inFolder: "in",
    deletedBookmark: "I've deleted the bookmark",
    foundBookmarks: "I found",
    bookmarksMatching: "bookmarks matching",
    noBookmarksFoundFor: "I couldn't find any bookmarks matching",
    foundFolders: "I found these folders",
    noFoldersFoundFor: "I couldn't find any folders matching",
    movedBookmark: "I've moved the bookmark",
    noFolders: "You don't have any folders yet.",
    createdFolder: "I have created the folder",
    renamedFolder: "I have renamed the folder",
    to: "to",
    alreadyExists: "already exists.",
    andAllItsContents: "and all its contents",
    deletedFolder: "I have deleted the folder",
    deleteFolderCancelled: "Folder deletion cancelled",
    viewChanged: "View changed to",
    invalidView: "Invalid view mode",
    themeChanged: "Theme changed to",
    invalidTheme: "Invalid theme",
    sortChanged: "Sort order changed to",
    invalidSort: "Invalid sort type",
    checkingLinks:
      "Started checking for broken links. Results will appear in the UI.",
    helpGuide: `
  <h4>Help Guide:</h4>
  <ol>
    <li><strong>Natural Language Queries:</strong><br>
      - Ask freely, e.g., <code>"How many bookmarks do I have?"</code>, <code>"Show my bookmarks"</code>, or <code>"Find bookmarks about technology"</code>.<br>
      - The bot will interpret and respond with bookmark actions or answers.
    </li>
    <li><strong>Add Bookmark:</strong><br>
      - Command: <code>"bookmark add https://example.com title 'My Page' to folder News"</code><br>
      - Or use the "Create Folder" button in the sidebar.
    </li>
    <li><strong>Move Bookmark:</strong><br>
      - Command: <code>"move bookmark 'My Page' to folder News"</code> or <code>"move bookmark id 123 to folder News"</code>.<br>
      - Or ask: <code>"Move the bookmark titled 'My Page' to the News folder"</code> or <code>"Move bookmark ID 123 to the News folder"</code>.
    </li>
    <li><strong>Search Bookmarks:</strong><br>
      - Command: <code>"search bookmarks keyword"</code> or ask: <code>"Find bookmarks with the keyword technology"</code>.<br>
      - Use the search bar or the "Sort: Default" dropdown for manual search.
    </li>
    <li><strong>Search Folders:</strong><br>
      - Command: <code>"search folders keyword"</code> or ask: <code>"Which folders have News in their name?"</code>.
    </li>
    <li><strong>List Bookmarks:</strong><br>
      - Command: <code>"list bookmarks"</code> or ask: <code>"What bookmarks do I have?"</code>.<br>
      - Results will show the title, URL, and ID of each bookmark.
    </li>
    <li><strong>Edit Bookmark:</strong><br>
      - Command: <code>"edit bookmark https://example.com title 'New Title' to folder Work"</code> or <code>"edit bookmark id 123 title 'New Title' to folder Work"</code>.<br>
      - Or ask: <code>"Rename the bookmark https://example.com to New Title"</code> or <code>"Edit bookmark ID 123 to title 'New Title' in folder Work"</code>.
    </li>
    <li><strong>Delete Bookmark:</strong><br>
      - Command: <code>"delete bookmark https://example.com"</code>, <code>"delete bookmark titled 'My Page'"</code>, or <code>"delete bookmark id 123"</code>.<br>
      - Or ask: <code>"Delete my bookmark https://example.com"</code> or <code>"Delete bookmark ID 123"</code>.<br>
      - <strong>Note:</strong> You will be prompted to confirm before deleting a bookmark.
    </li>
    <li><strong>Create Folder:</strong><br>
      - Command: <code>"create folder 'New Folder Name'"</code> or ask: <code>"Make a new folder called 'Work Projects'"</code>.<br>
      - To specify a parent folder: <code>"create folder 'Sub Folder' in 'Parent Folder'"</code>.
    </li>
    <li><strong>Rename Folder:</strong><br>
      - Command: <code>"rename folder 'Old Name' to 'New Name'"</code> or ask: <code>"Change the name of folder 'Work' to 'Office'"</code>.
    </li>
    <li><strong>Delete Folder:</strong><br>
      - Command: <code>"delete folder 'Folder Name'"</code> or ask: <code>"Remove the 'Temporary' folder"</code>.<br>
      - <strong>Note:</strong> You will be prompted to confirm before deleting a folder and its contents.
    </li>
    <li><strong>Change View Mode:</strong><br>
      - Command: <code>"change view to card"</code> or ask: <code>"Switch to tree view"</code>.<br>
      - Available views: <code>list</code>, <code>detail</code>, <code>card</code>, <code>tree</code>.
    </li>
    <li><strong>Change Theme:</strong><br>
      - Command: <code>"change theme to dark"</code> or ask: <code>"Apply the dracula theme"</code>.<br>
      - Available themes: <code>light</code>, <code>dark</code>, <code>dracula</code>, <code>onedark</code>, <code>tet</code>, <code>system</code>.
    </li>
    <li><strong>Change Sort Order:</strong><br>
      - Command: <code>"sort by name (A-Z)"</code> or ask: <code>"Change sorting to most visited"</code>.<br>
      - Available sorts: <code>default</code>, <code>favorites</code>, <code>most-visited</code>, <code>old</code>, <code>last-opened</code>, <code>a-z</code>, <code>z-a</code>, <code>domain</code>.
    </li>
    <li><strong>Check Link Health:</strong><br>
      - Command: <code>"check links"</code> or ask: <code>"Check my bookmarks for broken links"</code>.<br>
      - The bot will initiate a scan and report progress in the UI.
    </li>
    <li><strong>Bot Features:</strong><br>
      - Configure in "Configure Chatbot" for suggestions.<br>
      - The bot understands natural questions and commands to manage bookmarks, including by ID.
    </li>
    <li><strong>Recommended Websites to Bookmark:</strong><br>
      - You can add useful sites to your Bookmark Bar for quick access, such as:<br>
       - Command: <code>"Suggest me 3 websites about python"</code>
       - <code>" Suggest me 3 websites about {the keyword you want to search}"</code>
    </li>
    <li><strong>Export/Import Bookmarks:</strong><br>
      - Access via the "Settings" menu.
    </li>
  </ol>
`,

    clarifyBookmark:
      "I found multiple bookmarks named '{title}'. Please provide the URL or folder to specify which one.",
    noBookmarks: "I couldn't find a bookmark with {0}.",
    updatedBookmark: "I've updated the bookmark",
    inFolder: "in",
    naturalLanguagePrompt:
      "I don't know. Try commands like 'delete bookmark ID 123' or 'rename bookmark ID 456 to NewTitle'.",
    markedFavorite: "I've marked the bookmark",
    unmarkedFavorite: "I've removed the bookmark from favorites",
    showBookmarkIds: "Show Bookmark IDs",
    hideBookmarkIds: "Hide Bookmark IDs",
    localStorageSettingsTitle: "Local Storage Settings",
    saveSearchQuery: "Save Search Query",
    saveSelectedFolderId: "Save Selected Folder",
    saveSortType: "Save Sort Type",
    saveViewMode: "Save View Mode",
    saveCollapsedFolders: "Save Collapsed Folders",
    saveCheckboxesVisible: "Save Checkboxes Visibility",
    allTags: "All Tags",
    viewDetail: "View Details",
    manageTags: "Manage Tags",
    selectTag: "Select Tag",
    tagExists: "Tag already exists",
    tagLimitError: "Cannot add more than 10 tags per bookmark",
    saveSelectedTag: "Save Selected Tags",
    addTag: "Add Tag",
    newTagPlaceholder: "Enter tag name...",
    currentTagsLabel: "Current Tags:",
    addNewTagLabel: "Add New Tag:",
    tagBgColorLabel: "BG",
    tagTextColorLabel: "Text",
    addFromExistingLabel: "Or add from existing:",
    doneLabel: "Done",
    tagLimitReached: "Tag limit reached",
    detailDateAdded: "Date Added",
    detailFolder: "Folder",
    includeFolderPath: "Include Folder Path (for CSV)",
    includeFolderPathDescription: "Add full folder path (for CSV)",
    includeIconData: "Include icon data (Base64)",
    includeIconDataDescription: "Add favicon data to bookmarks",
    exportOnlySelected: "Only export selected bookmarks",
    exportOnlySelectedDescription:
      "If any bookmarks are checked in the main list, export only those",
    pinSuccess: "Bookmark pinned!",
    unpinSuccess: "Bookmark unpinned!",
    pinToTop: "Pin to Top",
    unpin: "Unpin from Top",
    errorCannotMoveFolderToSelf: "Cannot move folder to itself.",
    errorCannotMoveFolderToDescendant: "Cannot move folder to its descendant.",
    organizeFolders: "Organize Folders",
    organizeFoldersTitle: "Organize Folders",
    moveToFolderTitle: "Move Folder",
    moveFolderSuccess: "Folder moved successfully!",
    filtersTitle: "Filters",
    searchTitle: "Search",
    folderActionsTitle: "Folder actions",
    selectionTitle: "Selection",
    healthSortAll: "Sort by Health: All",
    healthSortDead: "Dead Links",
    healthSortSuspicious: "Suspicious Links",
    healthSortSafe: "Safe Links",
    generateQrCode: "Generate QR",
    noDuplicatesFound: "No duplicate bookmarks found.",
    duplicatesRemoved: "duplicate(s) removed.",
    checkLinks: "Check Links",
    checkDuplicates: "Check Duplicates",
    bookmarkActionsTitle: "Bookmark Actions",
    appSettingsTitle: "Application Settings",
    extensionOptionsTitle: "Extension Options",
    bookmarkHealthTitle: "Bookmark Health & Duplicates",
    bookmarkHealthSmallTitle: "Check Bookmarks",
    quickOpenTitle: "Quick Open Action",
    quickOpenPopup: "Default Popup",
    quickOpenSidePanel: "Default Side Panel",
    quickOpenWeb: "Default Web Tab",
  },
  vi: {
    welcomeMessage: "Chào mừng đến với Zero Bookmark Manager Chat!",
    welcomeSubMessage: "Tôi có thể giúp gì cho bạn hôm nay?",
    startButton: "Bắt đầu Chat",
    allBookmarks: "Tất cả Bookmarks",
    sortDefault: "Sắp xếp: Mặc định",
    sortNew: "Mới đến Cũ",
    sortOld: "Cũ đến Mới",
    sortLastOpened: "Theo Lần Mở Cuối",
    sortAZ: "A đến Z",
    sortZA: "Z đến A",
    sortFavorites: "Yêu thích",
    sortMostVisited: "Truy cập Nhiều nhất",
    sortDomain: "Theo tên miền",
    createFolder: "Tạo Thư mục",
    addToFolder: "Thêm vào Thư mục",
    deleteFolder: "Xóa Thư mục",
    settings: "Cài đặt",
    exportBookmarks: "Xuất Bookmarks",
    importBookmarks: "Nhập Bookmarks",
    selectAll: "Chọn Tất cả",
    showCheckboxes: "Hiển thị CheckBox",
    hideCheckboxes: "Ẩn CheckBox",
    searchPlaceholder: "Tìm kiếm Bookmarks...",
    renameTitle: "Đổi tên",
    renameFolder: "Đổi tên Thư mục",
    renamePlaceholder: "Nhập tên mới...",
    addToFolderTitle: "Thêm vào Thư mục",
    selectFolder: "Chọn Thư mục",
    newFolderPlaceholder: "Nhập tên thư mục muốn thêm",
    createNewFolder: "Tạo",
    save: "Lưu",
    cancel: "Hủy",
    totalBookmarks: "Tổng Bookmarks",
    scrollToTop: "Cuộn lên Đầu",
    clear: "Xóa",
    deleteConfirm: "Bạn có chắc chắn muốn xóa Bookmark này không?",
    deleteFolderConfirm:
      "Bạn có chắc chắn muốn xóa thư mục này không? Các Bookmark có trong thư mục khác sẽ được giữ lại.",
    confirmDeleteTag: "Bạn có chắc chắn muốn xóa thẻ này khỏi bookmark không?",
    deleteTagSuccess: "Đã xóa thẻ thành công!",
    discardFolderPrompt: "Bạn đã nhập tên thư mục nhưng chưa lưu. Hủy bỏ nó?",
    noBookmarks: "Không tìm thấy Bookmark. Vui lòng kiểm tra quyền truy cập.",
    emptyTitleError: "Tiêu đề không được để trống",
    emptyFolderError: "Tên thư mục không được để trống",
    selectFolderError: "Chọn một thư mục hoặc tạo mới",
    errorUnexpected: "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.",
    clearRenameAria: "Xóa nội dung nhập đổi tên",
    clearSearchAria: "Xóa nội dung tìm kiếm",
    settingsButtonAria: "Mở menu cài đặt",
    addToFolderOption: "Thêm vào Thư mục",
    deleteBookmarkOption: "Xóa",
    renameBookmarkOption: "Đổi tên",
    editInNewTabOption: "Mở Tab Web",
    openSidePanel: "Mở popup bên phải",
    deleteBookmarks: "Xóa bookmark",
    importSuccess: "Bookmark đã được nhập thành công!",
    importDuplicatePrompt:
      "Một số Bookmark đã tồn tại (cùng URL). Bạn có muốn nhập các Bookmark không trùng lặp không?",
    importInvalidFile:
      "Định dạng tệp không hợp lệ. Vui lòng chọn tệp JSON Bookmark hợp lệ.",
    importError: "Không thể nhập Bookmark. Vui lòng thử lại.",
    deleteBookmarkSuccess: "Bookmark đã được xóa thành công!",
    exportPrompt:
      "Chọn định dạng xuất: JSON hoặc HTML (dữ liệu sẽ được lưu dưới dạng JSON).",
    createFolderSuccess: "Thư mục được tạo thành công!",
    successTitle: "Thành công",
    errorTitle: "Lỗi",
    confirmTitle: "Xác nhận",
    renameSuccess: "Bookmark được đổi tên thành công!",
    addToFolderSuccess:
      "Đã thêm bookmark vào thư mục (Tải lại để cập nhật dữ liệu).",
    createFolderSuccess: "Thư mục được tạo thành công!",
    duplicateTitleError: "Tiêu đề đã tồn tại trong thư mục này",
    emptyTitleError: "Vui lòng nhập tiêu đề",
    emptyFolderError: "Vui lòng nhập tên thư mục hoặc chọn một thư mục",
    noBookmarksSelected: "Không có Bookmark nào được chọn",
    selectFolderError: "Vui lòng chọn một thư mục",
    errorUnexpected: "Đã xảy ra lỗi không mong muốn",
    restartExtension: "Vui lòng thử lại hoặc khởi động lại extension.",
    renamePlaceholder: "Nhập tên Bookmark mới",
    newFolderPlaceholder: "Nhập tên thư mục",
    selectFolder: "Chọn Thư mục",
    exportTitle: "Xuất Bookmarks",
    advancedSettings: "Cài đặt Nâng cao (HTML & CSV)",
    includeCreationDates: "Bao gồm ngày tạo",
    includeFolderModDates: "Bao gồm ngày chỉnh sửa thư mục",
    popupSubtitle: "Chọn định dạng xuất và cài đặt bạn muốn",
    exportFormat: "Định dạng Xuất",
    jsonDescription: "Định dạng đọc bằng máy (backup và khôi phục với import)",
    htmlDescription: "Trang web tương tác",
    csvDescription: "Dữ liệu bảng (dễ dàng mở trong Excel/Sheets)",
    netscapeDescription: "Định dạng trình duyệt tiêu chuẩn",
    includeCreationDatesDescription: "Thêm dấu thời gian tạo",
    includeFolderModDatesDescription: "Thêm dấu thời gian thư mục",
    exporting: "Đang xuất...",
    bookmarksTitle: "Bộ Sưu Tập Bookmarks Của Tôi",
    bookmarksHeader: "Bookmarks Của Tôi",
    exportedOn: "Đã in vào ngày",
    loadingBookmarks: "Đang tải bookmarks...",
    generatedBy: "Được tạo bởi Zero Bookmark Manager Extension",
    bookmarks: "bookmark",
    folders: "thư mục",
    created: "Đã tạo",
    modified: "Đã chỉnh sửa",
    unnamedFolder: "Thư mục không tên",
    notAvailable: "N/A",
    scrollToTop: "Scroll to Top",
    aiTitle: "Cấu hình AI Chatbot",
    favourite: "Yêu thích",
    removeFavourite: "Bỏ yêu thích",
    favoriteSuccess: "Đã thêm bookmark vào yêu thích!",
    unfavoriteSuccess: "Đã xóa bookmark khỏi yêu thích!",
    helpGuideTitle: "Hướng Dẫn",
    exportChatHistory: "Xuất Lịch Sử Chat",
    maximizeMinimize: "Phóng To/Thu Nhỏ",
    editAIConfig: "Chỉnh Sửa Cấu Hình AI",
    closeChat: "Đóng Chat",
    chatToggle: "Mở Chat",
    noChatHistory: "Không có lịch sử chat",
    loadingChat: "Đang xử lý...",
    moveBookmarkSuccess: "Đã chuyển bookmark thành công",
    moveBookmarkError: "Không tìm thấy bookmark hoặc thư mục không hợp lệ",
    searchFolderResult: "Các thư mục tìm thấy",
    noFoldersFound: "Không tìm thấy thư mục cho",
    aiBookmarkResponse: "Phản hồi AI",
    notSupported:
      "Xin lỗi, tôi chỉ có thể giúp với các tác vụ liên quan đến bookmark hoặc các câu hỏi đơn giản như giờ hoặc ngày.",
    youHave: "Bạn có",
    hereAreYourBookmarks: "Đây là danh sách bookmark của bạn",
    hereAreYourFolders: "Đây là danh sách thư mục của bạn",
    hereAreBookmarksInFolder: "Đây là danh sách bookmark trong thư mục",
    noBookmarksInFolder: "Không có bookmark trong thư mục này",
    addedBookmarkToFolder: "Tôi đã thêm bookmark",
    toFolder: "vào thư mục",
    updatedBookmark: "Tôi đã cập nhật bookmark",
    inFolder: "trong",
    deletedBookmark: "Tôi đã xóa bookmark",
    foundBookmarks: "Tôi tìm thấy",
    bookmarksMatching: "bookmark khớp với",
    noBookmarksFoundFor: "Tôi không tìm thấy bookmark nào khớp với",
    foundFolders: "Tôi tìm thấy các thư mục sau",
    noFoldersFoundFor: "Tôi không tìm thấy thư mục nào khớp với",
    movedBookmark: "Tôi đã chuyển bookmark",
    noFolders: "Bạn chưa có thư mục nào.",
    createdFolder: "Tôi đã tạo thư mục",
    renamedFolder: "Tôi đã đổi tên thư mục",
    to: "thành",
    alreadyExists: "đã tồn tại.",
    andAllItsContents: "và tất cả nội dung của nó",
    deletedFolder: "Tôi đã xóa thư mục",
    deleteFolderCancelled: "Hủy xóa thư mục",
    viewChanged: "Chế độ xem đã thay đổi thành",
    invalidView: "Chế độ xem không hợp lệ",
    themeChanged: "Chủ đề đã thay đổi thành",
    invalidTheme: "Chủ đề không hợp lệ",
    sortChanged: "Thứ tự sắp xếp đã thay đổi thành",
    invalidSort: "Kiểu sắp xếp không hợp lệ",
    checkingLinks:
      "Đã bắt đầu kiểm tra các liên kết hỏng. Kết quả sẽ hiển thị trên giao diện.",
    helpGuide: `
        <h4>Hướng Dẫn:</h4>
          <ol>
            <li><strong>Câu hỏi Ngôn ngữ Tự nhiên:</strong><br>
              - Hỏi tự do, ví dụ: <code>"Tôi có bao nhiêu bookmark?"</code>, <code>"Hiển thị bookmark của tôi"</code>, hoặc <code>"Tìm bookmark về công nghệ"</code>.<br>
              - AI sẽ diễn giải và trả lời bằng hành động bookmark hoặc câu trả lời.
            </li>
            <li><strong>Thêm Bookmark:</strong><br>
              - Lệnh: <code>"bookmark add https://example.com title 'Trang Của Tôi' to folder Tin Tức"</code><br>
              - Hoặc dùng nút "Tạo Thư mục" trong sidebar.
            </li>
            <li><strong>Di chuyển Bookmark:</strong><br>
              - Lệnh: <code>"chuyển bookmark 'Trang Của Tôi' sang thư mục Tin Tức"</code> hoặc <code>"chuyển bookmark id 123 sang thư mục Tin Tức"</code>.<br>
              - Hoặc hỏi: <code>"Chuyển bookmark có tiêu đề 'Trang Của Tôi' sang thư mục Tin Tức"</code> hoặc <code>"Chuyển bookmark ID 123 sang thư mục Tin Tức"</code>.
            </li>
            <li><strong>Tìm kiếm Bookmark:</strong><br>
              - Lệnh: <code>"tìm bookmark từ khóa"</code> hoặc hỏi: <code>"Tìm bookmark có từ khóa công nghệ"</code>.<br>
              - Dùng thanh tìm kiếm hoặc dropdown "Sắp xếp: Mặc định" để tìm thủ công.
            </li>
            <li><strong>Tìm kiếm Thư mục:</strong><br>
              - Lệnh: <code>"tìm thư mục từ khóa"</code> hoặc hỏi: <code>"Thư mục nào có từ News trong tên?"</code>.
            </li>
            <li><strong>Liệt kê Bookmark:</strong><br>
              - Lệnh: <code>"danh sách bookmark"</code> hoặc hỏi: <code>"Tôi có những bookmark nào?"</code>.<br>
              - Kết quả sẽ hiển thị tiêu đề, URL và ID của bookmark.
            </li>
            <li><strong>Sửa Bookmark:</strong><br>
              - Lệnh: <code>"edit bookmark https://example.com title 'Tiêu Đề Mới' to folder Công Việc"</code> hoặc <code>"edit bookmark id 123 title 'Tiêu Đề Mới' to folder Công Việc"</code>.<br>
              - Hoặc hỏi: <code>"Đổi tên bookmark https://example.com thành Tiêu Đề Mới"</code> hoặc <code>"Sửa bookmark ID 123 thành tiêu đề 'Tiêu Đề Mới' trong thư mục Công Việc"</code>.
            </li>
            <li><strong>Xóa Bookmark:</strong><br>
              - Lệnh: <code>"delete bookmark https://example.com"</code>, <code>"delete bookmark titled 'Trang Của Tôi'"</code>, hoặc <code>"delete bookmark id 123"</code>.<br>
              - Hoặc hỏi: <code>"Xóa bookmark https://example.com của tôi"</code> hoặc <code>"Xóa bookmark ID 123"</code>.<br>
              - <strong>Lưu ý:</strong> Bạn sẽ được yêu cầu xác nhận trước khi xóa bookmark.
            </li>
            <li><strong>Tạo Thư mục:</strong><br>
              - Lệnh: <code>"tạo thư mục 'Tên Thư mục Mới'"</code> hoặc hỏi: <code>"Tạo một thư mục mới tên 'Dự án Công việc'"</code>.<br>
              - Để chỉ định thư mục cha: <code>"tạo thư mục 'Thư mục Con' trong 'Thư mục Cha'"</code>.
            </li>
            <li><strong>Đổi tên Thư mục:</strong><br>
              - Lệnh: <code>"đổi tên thư mục 'Tên Cũ' thành 'Tên Mới'"</code> hoặc hỏi: <code>"Đổi tên thư mục 'Công việc' thành 'Văn phòng'"</code>.
            </li>
            <li><strong>Xóa Thư mục:</strong><br>
              - Lệnh: <code>"xóa thư mục 'Tên Thư mục'"</code> hoặc hỏi: <code>"Xóa thư mục 'Tạm thời'"</code>.<br>
              - <strong>Lưu ý:</strong> Bạn sẽ được yêu cầu xác nhận trước khi xóa thư mục và tất cả nội dung của nó.
            </li>
            <li><strong>Thay đổi Chế độ Xem:</strong><br>
              - Lệnh: <code>"thay đổi chế độ xem thành card"</code> hoặc hỏi: <code>"Chuyển sang chế độ xem cây"</code>.<br>
              - Các chế độ xem có sẵn: <code>list</code>, <code>detail</code>, <code>card</code>, <code>tree</code>.
            </li>
            <li><strong>Thay đổi Chủ đề:</strong><br>
              - Lệnh: <code>"thay đổi chủ đề thành tối"</code> hoặc hỏi: <code>"Áp dụng chủ đề dracula"</code>.<br>
              - Các chủ đề có sẵn: <code>light</code>, <code>dark</code>, <code>dracula</code>, <code>onedark</code>, <code>tet</code>, <code>system</code>.
            </li>
            <li><strong>Thay đổi Thứ tự Sắp xếp:</strong><br>
              - Lệnh: <code>"sắp xếp theo tên (A-Z)"</code> hoặc hỏi: <code>"Thay đổi sắp xếp thành được truy cập nhiều nhất"</code>.<br>
              - Các kiểu sắp xếp có sẵn: <code>default</code>, <code>favorites</code>, <code>most-visited</code>, <code>old</code>, <code>last-opened</code>, <code>a-z</code>, <code>z-a</code>, <code>domain</code>.
            </li>
            <li><strong>Kiểm tra Tình trạng Liên kết:</strong><br>
              - Lệnh: <code>"kiểm tra liên kết"</code> hoặc hỏi: <code>"Kiểm tra các bookmark của tôi xem có liên kết hỏng không"</code>.<br>
              - Bot sẽ bắt đầu quét và báo cáo tiến độ trên giao diện.
            </li>
            <li><strong>Tính năng AI:</strong><br>
              - Cấu hình trong "Cấu hình AI Chatbot" để gợi ý.<br>
              - AI hiểu các câu hỏi và lệnh tự nhiên để quản lý bookmark, bao gồm sử dụng ID.
            </li>
            <li><strong>Trang web Đề xuất để Bookmark:</strong><br>
              - Bạn có thể thêm các trang hữu ích vào Thanh Bookmark để truy cập nhanh, ví dụ:<br>
               - Lệnh: <code>"Đề xuất cho tôi 3 trang web về python"</code>
               - <code>"Đề xuất cho tôi 3 trang web {tên bạn muốn tìm}"</code>
            </li>
            <li><strong>Xuất/Nhập Bookmark:</strong><br>
              - Truy cập qua menu "Cài đặt".
            </li>
          </ol>
        `,
    clarifyBookmark:
      "Tui tìm thấy nhiều bookmark tên '{title}'. Bạn muốn chỉnh sửa cái nào? Hãy cung cấp URL hoặc thư mục.",
    noBookmarks: "Tui không tìm thấy bookmark nào có {0}.",
    updatedBookmark: "Tui đã cập nhật bookmark",
    inFolder: "trong",
    naturalLanguagePrompt:
      "Tui không biết. Thử lệnh như 'xóa bookmark ID 123' hoặc 'đổi tên bookmark ID 456 thành NewTitle'.",
    markedFavorite: "Tui đã đánh dấu bookmark",
    unmarkedFavorite: "Tui đã bỏ đánh dấu yêu thích cho bookmark",
    showBookmarkIds: "Hiển thị ID Bookmark",
    hideBookmarkIds: "Ẩn ID Bookmark",
    localStorageSettingsTitle: "Cài đặt Bộ nhớ tại web",
    saveSearchQuery: "Lưu Truy vấn Tìm kiếm",
    saveSelectedFolderId: "Lưu Thư mục Đã chọn",
    saveSortType: "Lưu Kiểu Sắp xếp",
    saveViewMode: "Lưu Chế độ Xem",
    saveCollapsedFolders: "Lưu Thư mục Thu gọn",
    saveCheckboxesVisible: "Lưu Hiển thị Hộp kiểm",
    allTags: "Tất cả Thẻ",
    viewDetail: "Xem Chi tiết",
    manageTags: "Quản lý Thẻ",
    selectTag: "Chọn Thẻ",
    tagExists: "Thẻ đã tồn tại",
    tagLimitError: "Không thể thêm quá 10 thẻ cho mỗi bookmark",
    saveSelectedTag: "Lưu Thẻ Đã chọn",
    addTag: "Thêm Thẻ",
    newTagPlaceholder: "Nhập tên thẻ...",
    currentTagsLabel: "Các thẻ hiện tại:",
    addNewTagLabel: "Thêm thẻ mới:",
    tagBgColorLabel: "Nền",
    tagTextColorLabel: "Chữ",
    addFromExistingLabel: "Hoặc thêm từ các thẻ đã có:",
    doneLabel: "Xong",
    tagLimitReached: "Đã đạt giới hạn thẻ",
    detailDateAdded: "Ngày Thêm",
    detailFolder: "Thư mục",
    includeFolderPath: "Bao gồm Đường dẫn Thư mục (cho CSV)",
    includeFolderPathDescription: "Thêm đường dẫn đầy đủ của thư mục (cho CSV)",
    includeIconData: "Bao gồm dữ liệu icon (Base64)",
    includeIconDataDescription: "Thêm favicon cho từng bookmark",
    exportOnlySelected: "Chỉ xuất các bookmark đã chọn",
    exportOnlySelectedDescription:
      "Nếu có bookmark được tick trong danh sách chính, chỉ xuất những bookmark đó",
    pinSuccess: "Đã ghim bookmark!",
    unpinSuccess: "Đã bỏ ghim bookmark!",
    pinToTop: "Ghim lên Đầu",
    unpin: "Bỏ ghim khỏi Đầu",
    errorCannotMoveFolderToSelf: "Không thể di chuyển thư mục vào chính nó.",
    errorCannotMoveFolderToDescendant:
      "Không thể di chuyển thư mục vào thư mục con của nó.",
    organizeFolders: "Sắp xếp Thư mục",
    organizeFoldersTitle: "Sắp xếp Thư mục",
    moveToFolderTitle: "Di chuyển Thư mục",
    moveFolderSuccess: "Đã di chuyển thư mục thành công!",
    filtersTitle: "Bộ lọc",
    searchTitle: "Tìm kiếm",
    folderActionsTitle: "Thao tác thư mục",
    selectionTitle: "Lựa chọn",
    healthSortAll: "Tất cả",
    healthSortDead: "Liên kết hỏng",
    healthSortSuspicious: "Liên kết đáng ngờ",
    healthSortSafe: "Liên kết an toàn",
    generateQrCode: "Tạo mã QR",
    noDuplicatesFound: "Không tìm thấy bookmark trùng lặp.",
    duplicatesRemoved: "bookmark trùng lặp đã được xóa.",
    checkLinks: "Kiểm tra liên kết",
    checkDuplicates: "Kiểm tra trùng lặp",
    bookmarkActionsTitle: "Thao tác Bookmark",
    appSettingsTitle: "Cài đặt ứng dụng",
    extensionOptionsTitle: "Tùy chọn tiện ích",
    bookmarkHealthTitle: "Kiểm tra Bookmark",
    bookmarkHealthSmallTitle: "Kiểm tra Bookmark",
    quickOpenTitle: "Hành động Mở Nhanh",
    quickOpenPopup: "Popup mặc định",
    quickOpenSidePanel: "Mở panel mặc định",
    quickOpenWeb: "Mở web mặc định",
  },
}

export function safeChromeBookmarksCall(method, args, callback) {
  try {
    if (!chrome || !chrome.bookmarks || !chrome.bookmarks[method]) {
      console.error(`chrome.bookmarks.${method} is not available`)
      const language = localStorage.getItem("appLanguage") || "en"
      showCustomPopup(translations[language].errorUnexpected, "error", false)
      callback(null)
      return
    }
    chrome.bookmarks[method](...args, (result) => {
      if (chrome.runtime.lastError) {
        console.error(`Error in ${method}:`, chrome.runtime.lastError.message)
        const language = localStorage.getItem("appLanguage") || "en"
        showCustomPopup(translations[language].errorUnexpected, "error", false)
        callback(null)
        return
      }
      callback(result)
    })
  } catch (error) {
    console.error(`Unexpected error in ${method}:`, error)
    const language = localStorage.getItem("appLanguage") || "en"
    showCustomPopup(translations[language].errorUnexpected, "error", false)
    callback(null)
  }
}

export function debounce(func, wait) {
  let timeout
  return function (...args) {
    clearTimeout(timeout)
    timeout = setTimeout(() => func.apply(this, args), wait)
  }
}

export function showCustomPopup(
  message,
  type = "success",
  autoClose = true,
  onConfirm = null,
  showCancel = false,
) {
  const popup = document.getElementById("custom-popup")
  const title = document.getElementById("custom-popup-title")
  const messageEl = document.getElementById("custom-popup-message")
  const okButton = document.getElementById("custom-popup-ok")
  const cancelButton = document.getElementById("custom-popup-cancel")
  const language = localStorage.getItem("appLanguage") || "en"

  if (!popup || !title || !messageEl || !okButton) {
    console.error("Custom popup elements missing", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
      cancelButton: !!cancelButton,
    })
    return
  }

  try {
    // Thiết lập tiêu đề theo loại popup
    if (type === "loading") {
      title.textContent = language === "vi" ? "Đang xử lý..." : "Loading..."
    } else if (type === "success") {
      title.textContent = translations[language].successTitle
    } else if (type === "error") {
      title.textContent = translations[language].errorTitle
    } else {
      // info, warning, ...
      title.textContent = language === "vi" ? "Thông báo" : "Notification"
    }

    messageEl.textContent = message
    popup.classList.remove("hidden")

    // Áp dụng class theo type để có thể style khác nhau (success, error, loading, warning,...)
    popup.classList.remove("success", "error", "loading", "warning", "info")
    if (type) {
      popup.classList.add(type)
    }

    const currentTheme =
      document.documentElement.getAttribute("data-theme") || "light"

    // Remove all possible theme classes
    const allThemes = ["light", "dark", "dracula", "onedark"]
    allThemes.forEach((theme) => {
      popup.classList.remove(`${theme}-theme`)
    })

    // Apply current theme to popup
    popup.classList.add(`${currentTheme}-theme`)

    const closePopup = () => {
      popup.classList.add("hidden")
      document.removeEventListener("keydown", handleKeydown)
    }

    okButton.onclick = () => {
      closePopup()
      if (onConfirm) onConfirm()
    }

    if (cancelButton) {
      if (showCancel) {
        cancelButton.classList.remove("hidden")
        cancelButton.onclick = () => closePopup()
      } else {
        cancelButton.classList.add("hidden")
      }
    }

    popup.onclick = (e) => {
      if (e.target === popup) {
        closePopup()
      }
    }

    const handleKeydown = (e) => {
      if (e.key === "Enter") {
        okButton.click()
      } else if (e.key === "Escape") {
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)

    if ((type === "success" || type === "info") && autoClose && !onConfirm) {
      setTimeout(closePopup, 5000)
    }
  } catch (error) {
    console.error("Error in showCustomPopup:", error)
  }
}

export function showCustomConfirm(message, onConfirm, onCancel) {
  const popup = document.getElementById("custom-popup")
  const title = document.getElementById("custom-popup-title")
  const messageEl = document.getElementById("custom-popup-message")
  const okButton = document.getElementById("custom-popup-ok")
  const language = localStorage.getItem("appLanguage") || "en"
  const buttonsContainer = popup?.querySelector(".rename-popup-buttons")

  if (!popup || !title || !messageEl || !okButton || !buttonsContainer) {
    console.error("Custom confirm popup elements missing", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
      buttonsContainer: !!buttonsContainer,
    })
    return
  }

  try {
    title.textContent = translations[language].confirmTitle || "Confirm"

    messageEl.textContent = message

    popup.classList.remove("hidden")

    const cancelButton = document.createElement("button")
    cancelButton.className = "button cancel"
    cancelButton.textContent = translations[language].cancel || "Cancel"

    buttonsContainer.appendChild(cancelButton)

    const isDarkMode = document.body.classList.contains("dark-theme")
    popup.classList.toggle("light-theme", !isDarkMode)
    popup.classList.toggle("dark-theme", isDarkMode)

    const closePopup = () => {
      popup.classList.add("hidden")
      if (buttonsContainer.contains(cancelButton)) {
        buttonsContainer.removeChild(cancelButton)
      }
      document.removeEventListener("keydown", handleKeydown)
    }

    okButton.onclick = () => {
      onConfirm()
      closePopup()
    }

    cancelButton.onclick = () => {
      if (onCancel) onCancel()
      closePopup()
    }

    popup.onclick = (e) => {
      if (e.target === popup) {
        if (onCancel) onCancel()
        closePopup()
      }
    }

    const handleKeydown = (e) => {
      if (e.key === "Enter") {
        onConfirm()
        closePopup()
      } else if (e.key === "Escape") {
        if (onCancel) onCancel()
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)
  } catch (error) {
    console.error("Error in showCustomConfirm:", error)
  }
}

export function showCustomGuide() {
  // Ensure DOM is loaded
  if (!document.getElementById("custom-guide")) {
    console.error(
      "Custom guide popup not found. Waiting for DOMContentLoaded...",
    )
    document.addEventListener("DOMContentLoaded", showCustomGuide)
    return
  }

  const popup = document.getElementById("custom-guide")
  const title = document.getElementById("custom-guide-title")
  const messageEl = document.getElementById("custom-guide-message")
  const okButton = document.getElementById("custom-guide-ok")
  const language = localStorage.getItem("appLanguage") || "en"

  // Log missing elements for debugging
  if (!popup || !title || !messageEl || !okButton) {
    console.error("Custom guide elements missing:", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
    })
    // Display a fallback error message
    if (document.getElementById("custom-popup")) {
      showCustomPopup(
        `${translations[language].errorTitle}: ${
          translations[language].errorUnexpected || "Unexpected error"
        }`,
        "error",
        true,
      )
    } else {
      alert("Error: Help guide cannot be displayed due to missing elements.")
    }
    return
  }

  try {
    title.textContent = translations[language].helpGuideTitle

    messageEl.innerHTML = translations[language].helpGuide

    popup.classList.remove("hidden")

    const isDarkMode = document.body.classList.contains("dark-theme")
    popup.classList.toggle("light-theme", !isDarkMode)
    popup.classList.toggle("dark-theme", isDarkMode)

    const closePopup = () => {
      popup.classList.add("hidden")
      document.removeEventListener("keydown", handleKeydown)
      document.removeEventListener("click", handleOutsideClick) // Thêm dòng này
    }

    okButton.onclick = () => closePopup()

    // Trong hàm showCustomGuide, thay thế phần event listener:
    const handleOutsideClick = (e) => {
      if (!popup.contains(e.target)) {
        closePopup()
      }
    }

    // Sử dụng click thay vì mousedown, và thêm một độ trễ nhỏ
    setTimeout(() => {
      document.addEventListener("click", handleOutsideClick)
    }, 100) // 100ms delay

    // Ngăn sự kiện click từ nội dung popup lan ra ngoài
    popup.addEventListener("click", (e) => {
      e.stopPropagation()
    })

    const handleKeydown = (e) => {
      if (e.key === "Enter" || e.key === "Escape") {
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)
  } catch (error) {
    console.error("Error in showCustomGuide:", error)
    if (document.getElementById("custom-popup")) {
      showCustomPopup(
        `${translations[language].errorTitle}: ${
          translations[language].errorUnexpected || "Unexpected error"
        }`,
        "error",
        true,
      )
    } else {
      alert("Error: Help guide cannot be displayed.")
    }
  }
}

export function showLocalStorageSettingsPopup() {
  const popup = document.getElementById("localstorage-settings-popup")
  const title = document.getElementById("localstorage-settings-title")
  const saveButton = document.getElementById("localstorage-settings-save")
  const cancelButton = document.getElementById("localstorage-settings-cancel")
  const language = localStorage.getItem("appLanguage") || "en"

  if (!popup || !title || !saveButton || !cancelButton) {
    console.error("Local storage settings popup elements missing:", {
      popup: !!popup,
      title: !!title,
      saveButton: !!saveButton,
      cancelButton: !!cancelButton,
    })
    showCustomPopup(translations[language].errorUnexpected, "error", true)
    return
  }

  // Set multilingual labels
  title.textContent = translations[language].localStorageSettingsTitle
  saveButton.textContent = translations[language].save
  cancelButton.textContent = translations[language].cancel

  // Debug checkbox visibility
  const checkboxes = document.querySelectorAll(
    '.localstorage-settings-container input[type="checkbox"]',
  )

  popup.classList.remove("hidden")

  // Apply current theme
  const currentTheme =
    document.documentElement.getAttribute("data-theme") || "light"
  const allThemes = ["light", "dark", "dracula", "onedark"]
  allThemes.forEach((theme) => popup.classList.remove(`${theme}-theme`))
  popup.classList.add(`${currentTheme}-theme`)
}

export function hideLocalStorageSettingsPopup() {
  const popup = document.getElementById("localstorage-settings-popup")
  if (popup) {
    popup.classList.add("hidden")
  }
}
