// components/utils.js
export const translations = {
  en: {
    welcomeMessage: "Welcome to Zero Bookmark Manager Chat!",
    welcomeSubMessage: "How can I assist you today?",
    startButton: "Start Chat",
    allBookmarks: "All Bookmarks",
    sortDefault: "Sort: Default",
    sortNew: "New to Old",
    sortOld: "Old to New",
    sortLastOpened: "By Last Opened",
    sortAZ: "A to Z",
    sortZA: "Z to A",
    sortFavorites: "Favorites",
    sortMostVisited: "Most Visited",
    sortDomain: "By Domain",
    createFolder: "Create Folder",
    addToFolder: "Add to Folder",
    deleteFolder: "Delete Folder",
    settings: "Settings",
    exportBookmarks: "Export Bookmarks",
    importBookmarks: "Import Bookmarks",
    selectAll: "Select All",
    showCheckboxes: "Show Checkboxes",
    hideCheckboxes: "Hide Checkboxes",
    searchPlaceholder: "Search bookmarks...",
    renameTitle: "Rename",
    renameFolder: "Rename Folder",
    renamePlaceholder: "Enter new name...",
    addToFolderTitle: "Add to Folder",
    moveToFolder: "Move to Folder",
    moveToFolderTitle: "Move Folder",
    selectFolder: "Select Folder",
    newFolderPlaceholder: "Name folder want to add",
    createNewFolder: "Create",
    save: "Save",
    cancel: "Cancel",
    totalBookmarks: "Total Bookmarks",
    scrollToTop: "Scroll to Top",
    clear: "Clear",
    deleteConfirm: "Are you sure you want to delete this bookmark?",
    deleteFolderConfirm:
      "Are you sure you want to delete this folder? Bookmarks that exist in other folders will be preserved.",
    confirmDeleteTag:
      "Are you sure you want to delete this tag from the bookmark?",
    deleteTagSuccess: "Tag deleted successfully!",
    discardFolderPrompt:
      "You entered a folder name but didn't save. Discard it?",
    noBookmarks: "No bookmarks found. Please check permissions.",
    emptyTitleError: "Title cannot be empty",
    emptyFolderError: "Folder name cannot be empty",
    selectFolderError: "Select a folder or create a new one",
    errorUnexpected: "Unexpected error occurred. Please try again.",
    clearRenameAria: "Clear rename input",
    clearSearchAria: "Clear search input",
    settingsButtonAria: "Open settings menu",
    addToFolderOption: "Add to Folder",
    deleteBookmarkOption: "Delete",
    renameBookmarkOption: "Rename",
    editInNewTabOption: "Open Web View",
    openSidePanel: "Open Side Panel",
    deleteBookmarks: "Delete bookmark",
    importSuccess: "Bookmarks imported successfully!",
    importDuplicatePrompt:
      "Some bookmarks already exist (same URL). Do you want to import the non-duplicate bookmarks?",
    importInvalidFile:
      "Invalid file format. Please select a valid JSON bookmark file.",
    importError: "Failed to import bookmarks. Please try again.",
    deleteBookmarkSuccess: "Bookmark deleted successfully!",
    exportPrompt:
      "Choose export format: JSON or HTML (data will be saved as JSON).",
    createFolderSuccess: "Folder created successfully!",
    confirmTitle: "Confirm",
    successTitle: "Success",
    errorTitle: "Error",
    renameSuccess: "Bookmark renamed successfully!",
    addToFolderSuccess:
      "Bookmark(s) added to folder successfully! (Reload to update data)",
    createFolderSuccess: "Folder created successfully!",
    duplicateTitleError: "Title already exists in this folder",
    emptyTitleError: "Please enter a title",
    emptyFolderError: "Please enter a folder name or select a folder",
    noBookmarksSelected: "No bookmarks selected",
    selectFolderError: "Please select a folder",
    errorUnexpected: "An unexpected error occurred",
    restartExtension: "Please try again or restart the extension.",
    renamePlaceholder: "Enter new bookmark name",
    newFolderPlaceholder: "Enter folder name",
    selectFolder: "Select Folder",
    exportTitle: "Export Bookmarks",
    advancedSettings: "Advanced Settings (HTML & CSV)",
    includeCreationDates: "Include creation dates",
    includeFolderModDates: "Include folder modification dates",
    popupSubtitle: "Choose your preferred export format and settings",
    exportFormat: "Export Format",
    jsonDescription: "Machine readable format (backup and restore with import)",
    htmlDescription: "Interactive web page",
    csvDescription: "Tabular data (easily open in Excel/Sheets)",
    netscapeDescription: "Standard browser format",
    includeCreationDatesDescription: "Add creation timestamps",
    includeFolderModDatesDescription: "Add folder timestamps",
    exporting: "Exporting...",
    bookmarksTitle: "My Bookmarks Collection",
    bookmarksHeader: "My Bookmarks",
    exportedOn: "Exported on",
    loadingBookmarks: "Loading bookmarks...",
    generatedBy: "Generated by Zero Bookmark Manager Extension",
    bookmarks: "bookmarks",
    folders: "folders",
    created: "Created",
    modified: "Modified",
    unnamedFolder: "Unnamed Folder",
    notAvailable: "N/A",
    scrollToTop: "Scroll to Top",
    aiTitle: "Configure AI Chatbot",
    favourite: "Favourite",
    removeFavourite: "Remove from Favorites",
    favoriteSuccess: "Bookmark added to favorites!",
    unfavoriteSuccess: "Bookmark removed from favorites!",
    helpGuideTitle: "Help Guide",
    exportChatHistory: "Export Chat History",
    maximizeMinimize: "Maximize/Minimize",
    editAIConfig: "Edit AI Config",
    closeChat: "Close Chat",
    chatToggle: "Open Chat",
    noChatHistory: "No chat history available",
    loadingChat: "Processing...",
    moveBookmarkSuccess: "Bookmark moved successfully",
    moveBookmarkError: "Bookmark not found or invalid folder",
    searchFolderResult: "Found folders",
    noFoldersFound: "No folders found for",
    aiBookmarkResponse: "AI Response",
    notSupported:
      "Sorry, I can only help with bookmark-related tasks or simple questions like the time or day.",
    youHave: "You have",
    hereAreYourBookmarks: "Here are your bookmarks",
    hereAreYourFolders: "Here are your folders",
    hereAreBookmarksInFolder: "Here are the bookmarks in folder",
    noBookmarksInFolder: "No bookmarks in this folder",
    addedBookmarkToFolder: "I've added the bookmark",
    toFolder: "to the folder",
    updatedBookmark: "I've updated the bookmark",
    inFolder: "in",
    deletedBookmark: "I've deleted the bookmark",
    foundBookmarks: "I found",
    bookmarksMatching: "bookmarks matching",
    noBookmarksFoundFor: "I couldn't find any bookmarks matching",
    foundFolders: "I found these folders",
    noFoldersFoundFor: "I couldn't find any folders matching",
    movedBookmark: "I've moved the bookmark",
    noFolders: "You don't have any folders yet.",
    createdFolder: "I have created the folder",
    renamedFolder: "I have renamed the folder",
    to: "to",
    alreadyExists: "already exists.",
    andAllItsContents: "and all its contents",
    deletedFolder: "I have deleted the folder",
    deleteFolderCancelled: "Folder deletion cancelled",
    viewChanged: "View changed to",
    invalidView: "Invalid view mode",
    themeChanged: "Theme changed to",
    invalidTheme: "Invalid theme",
    sortChanged: "Sort order changed to",
    invalidSort: "Invalid sort type",
    checkingLinks:
      "Started checking for broken links. Results will appear in the UI.",
    helpCommands: `
      <h4>Command List</h4>
      <ul>
        <li><strong>/help</strong> - Show this list</li>
        <li><strong>count bookmarks</strong> - Count bookmarks</li>
        <li><strong>count folders</strong> - Count folders</li>
        <li><strong>list bookmarks</strong> - List all bookmarks</li>
        <li><strong>list folders</strong> - List all folders</li>
        <li><strong>list bookmarks in folder "Work"</strong></li>
        <li><strong>use @Work to pick a folder</strong></li>
        <li><strong>add https://example.com to folder "Work"</strong></li>
        <li><strong>move bookmark "Title" to folder "Work"</strong></li>
        <li><strong>edit bookmark "Title"</strong></li>
        <li><strong>delete bookmark "Title"</strong></li>
        <li><strong>create folder "Work"</strong></li>
        <li><strong>rename folder "Old" to "New"</strong></li>
        <li><strong>delete folder "Work"</strong></li>
        <li><strong>search bookmarks "keyword"</strong></li>
        <li><strong>search folders "keyword"</strong></li>
        <li><strong>favorite bookmark "Title"</strong></li>
        <li><strong>change view to card</strong></li>
        <li><strong>change theme to dark</strong></li>
        <li><strong>sort by a-z</strong></li>
        <li><strong>check links</strong></li>
      </ul>
    `,
    helpGuide: `
  <h4>Help Guide:</h4>
  <ol>
    <li><strong>/help</strong><br>
      - Show the command list.
    </li>
    <li><strong>Count:</strong><br>
      - <code>"count bookmarks"</code>, <code>"count folders"</code>.
    </li>
    <li><strong>List:</strong><br>
      - <code>"list bookmarks"</code>, <code>"list folders"</code>.<br>
      - <code>"list bookmarks in folder \"Work\""</code>.<br>
      - Use <code>@Work</code> to pick a folder.
    </li>
    <li><strong>Add Bookmark:</strong><br>
      - <code>"add https://example.com to folder \"Work\""</code>.
    </li>
    <li><strong>Move Bookmark:</strong><br>
      - <code>"move bookmark \"Title\" to folder \"Work\""</code> or <code>"move bookmark id 123 to folder \"Work\""</code>.
    </li>
    <li><strong>Edit Bookmark:</strong><br>
      - <code>"edit bookmark \"Title\""</code> or <code>"edit bookmark id 123"</code>.
    </li>
    <li><strong>Delete Bookmark:</strong><br>
      - <code>"delete bookmark \"Title\""</code> or <code>"delete bookmark id 123"</code>.
    </li>
    <li><strong>Folders:</strong><br>
      - <code>"create folder \"Work\""</code>, <code>"rename folder \"Old\" to \"New\""</code>, <code>"delete folder \"Work\""</code>.
    </li>
    <li><strong>Search:</strong><br>
      - <code>"search bookmarks \"keyword\""</code>, <code>"search folders \"keyword\""</code>.
    </li>
    <li><strong>Favorite:</strong><br>
      - <code>"favorite bookmark \"Title\""</code>.
    </li>
    <li><strong>View / Theme / Sort:</strong><br>
      - <code>"change view to card"</code>, <code>"change theme to dark"</code>, <code>"sort by a-z"</code>.
    </li>
    <li><strong>Check Links:</strong><br>
      - <code>"check links"</code>.
    </li>
    <li><strong>Note:</strong><br>
      - Local mode only supports bookmark commands.
    </li>
  </ol>
`,

    clarifyBookmark:
      "I found multiple bookmarks named '{title}'. Please provide the URL or folder to specify which one.",
    noBookmarks: "I couldn't find a bookmark with {0}.",
    updatedBookmark: "I've updated the bookmark",
    inFolder: "in",
    naturalLanguagePrompt:
      "I don't know. Try commands like 'delete bookmark ID 123' or 'rename bookmark ID 456 to NewTitle'.",
    markedFavorite: "I've marked the bookmark",
    unmarkedFavorite: "I've removed the bookmark from favorites",
    showBookmarkIds: "Show Bookmark IDs",
    hideBookmarkIds: "Hide Bookmark IDs",
    localStorageSettingsTitle: "Local Storage Settings",
    saveSearchQuery: "Save Search Query",
    saveSelectedFolderId: "Save Selected Folder",
    saveSortType: "Save Sort Type",
    saveViewMode: "Save View Mode",
    saveCollapsedFolders: "Save Collapsed Folders",
    saveCheckboxesVisible: "Save Checkboxes Visibility",
    allTags: "All Tags",
    viewDetail: "View Details",
    manageTags: "Manage Tags",
    selectTag: "Select Tag",
    tagExists: "Tag already exists",
    tagLimitError: "Cannot add more than 10 tags per bookmark",
    saveSelectedTag: "Save Selected Tags",
    addTag: "Add Tag",
    newTagPlaceholder: "Enter tag name...",
    currentTagsLabel: "Current Tags:",
    addNewTagLabel: "Add New Tag:",
    tagBgColorLabel: "BG",
    tagTextColorLabel: "Text",
    addFromExistingLabel: "Or add from existing:",
    doneLabel: "Done",
    tagLimitReached: "Tag limit reached",
    detailDateAdded: "Date Added",
    detailFolder: "Folder",
    includeFolderPath: "Include Folder Path (for CSV)",
    includeFolderPathDescription: "Add full folder path (for CSV)",
    includeIconData: "Include icon data (Base64)",
    includeIconDataDescription: "Add favicon data to bookmarks",
    exportOnlySelected: "Only export selected bookmarks",
    exportOnlySelectedDescription:
      "If any bookmarks are checked in the main list, export only those",
    pinSuccess: "Bookmark pinned!",
    unpinSuccess: "Bookmark unpinned!",
    pinToTop: "Pin to Top",
    unpin: "Unpin from Top",
    errorCannotMoveFolderToSelf: "Cannot move folder to itself.",
    errorCannotMoveFolderToDescendant: "Cannot move folder to its descendant.",
    organizeFolders: "Organize Folders",
    organizeFoldersTitle: "Organize Folders",
    moveToFolderTitle: "Move Folder",
    moveFolderSuccess: "Folder moved successfully!",
    filtersTitle: "Filters",
    searchTitle: "Search",
    folderActionsTitle: "Folder actions",
    selectionTitle: "Selection",
    healthSortAll: "Sort by Health: All",
    healthSortDead: "Dead Links",
    healthSortSuspicious: "Suspicious Links",
    healthSortSafe: "Safe Links",
    generateQrCode: "Generate QR",
    noDuplicatesFound: "No duplicate bookmarks found.",
    duplicatesRemoved: "duplicate(s) removed.",
    checkLinks: "Check Links",
    checkDuplicates: "Check Duplicates",
    bookmarkActionsTitle: "Bookmark Actions",
    appSettingsTitle: "Application Settings",
    extensionOptionsTitle: "Extension Options",
    bookmarkHealthTitle: "Bookmark Health & Duplicates",
    bookmarkHealthSmallTitle: "Check Bookmarks",
    quickOpenTitle: "Quick Open Action",
    quickOpenPopup: "Default Popup",
    quickOpenSidePanel: "Default Side Panel",
    quickOpenWeb: "Default Web Tab",
    // Sidebar translations
    sidebarAllBookmarks: "All Bookmarks",
    sidebarFavorites: "Favorites",
    sidebarUnsorted: "Unsorted",
    sidebarRecentlyAdded: "Recently Added",
    sidebarFolders: "Folders",
    sidebarTags: "Tags",
    sidebarSort: "Sort",
    sidebarManage: "Manage",
    sidebarMoreFolders: "more folders",
    sidebarBookmarks: "bookmarks",
  },
  vi: {
    welcomeMessage: "Chào mừng đến với Zero Bookmark Manager Chat!",
    welcomeSubMessage: "Tôi có thể giúp gì cho bạn hôm nay?",
    startButton: "Bắt đầu Chat",
    allBookmarks: "Tất cả Bookmarks",
    sortDefault: "Sắp xếp: Mặc định",
    sortNew: "Mới đến Cũ",
    sortOld: "Cũ đến Mới",
    sortLastOpened: "Theo Lần Mở Cuối",
    sortAZ: "A đến Z",
    sortZA: "Z đến A",
    sortFavorites: "Yêu thích",
    sortMostVisited: "Truy cập Nhiều nhất",
    sortDomain: "Theo tên miền",
    createFolder: "Tạo Thư mục",
    addToFolder: "Thêm vào Thư mục",
    deleteFolder: "Xóa Thư mục",
    settings: "Cài đặt",
    exportBookmarks: "Xuất Bookmarks",
    importBookmarks: "Nhập Bookmarks",
    selectAll: "Chọn Tất cả",
    showCheckboxes: "Hiển thị CheckBox",
    hideCheckboxes: "Ẩn CheckBox",
    searchPlaceholder: "Tìm kiếm Bookmarks...",
    renameTitle: "Đổi tên",
    renameFolder: "Đổi tên Thư mục",
    renamePlaceholder: "Nhập tên mới...",
    addToFolderTitle: "Thêm vào Thư mục",
    moveToFolder: "Di chuyển đến Thư mục",
    moveToFolderTitle: "Di chuyển Thư mục",
    selectFolder: "Chọn Thư mục",
    newFolderPlaceholder: "Nhập tên thư mục muốn thêm",
    createNewFolder: "Tạo",
    save: "Lưu",
    cancel: "Hủy",
    totalBookmarks: "Tổng Bookmarks",
    scrollToTop: "Cuộn lên Đầu",
    clear: "Xóa",
    deleteConfirm: "Bạn có chắc chắn muốn xóa Bookmark này không?",
    deleteFolderConfirm:
      "Bạn có chắc chắn muốn xóa thư mục này không? Các Bookmark có trong thư mục khác sẽ được giữ lại.",
    confirmDeleteTag: "Bạn có chắc chắn muốn xóa thẻ này khỏi bookmark không?",
    deleteTagSuccess: "Đã xóa thẻ thành công!",
    discardFolderPrompt: "Bạn đã nhập tên thư mục nhưng chưa lưu. Hủy bỏ nó?",
    noBookmarks: "Không tìm thấy Bookmark. Vui lòng kiểm tra quyền truy cập.",
    emptyTitleError: "Tiêu đề không được để trống",
    emptyFolderError: "Tên thư mục không được để trống",
    selectFolderError: "Chọn một thư mục hoặc tạo mới",
    errorUnexpected: "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.",
    clearRenameAria: "Xóa nội dung nhập đổi tên",
    clearSearchAria: "Xóa nội dung tìm kiếm",
    settingsButtonAria: "Mở menu cài đặt",
    addToFolderOption: "Thêm vào Thư mục",
    deleteBookmarkOption: "Xóa",
    renameBookmarkOption: "Đổi tên",
    editInNewTabOption: "Mở Tab Web",
    openSidePanel: "Mở popup bên phải",
    deleteBookmarks: "Xóa bookmark",
    importSuccess: "Bookmark đã được nhập thành công!",
    importDuplicatePrompt:
      "Một số Bookmark đã tồn tại (cùng URL). Bạn có muốn nhập các Bookmark không trùng lặp không?",
    importInvalidFile:
      "Định dạng tệp không hợp lệ. Vui lòng chọn tệp JSON Bookmark hợp lệ.",
    importError: "Không thể nhập Bookmark. Vui lòng thử lại.",
    deleteBookmarkSuccess: "Bookmark đã được xóa thành công!",
    exportPrompt:
      "Chọn định dạng xuất: JSON hoặc HTML (dữ liệu sẽ được lưu dưới dạng JSON).",
    createFolderSuccess: "Thư mục được tạo thành công!",
    successTitle: "Thành công",
    errorTitle: "Lỗi",
    confirmTitle: "Xác nhận",
    renameSuccess: "Bookmark được đổi tên thành công!",
    addToFolderSuccess:
      "Đã thêm bookmark vào thư mục (Tải lại để cập nhật dữ liệu).",
    createFolderSuccess: "Thư mục được tạo thành công!",
    duplicateTitleError: "Tiêu đề đã tồn tại trong thư mục này",
    emptyTitleError: "Vui lòng nhập tiêu đề",
    emptyFolderError: "Vui lòng nhập tên thư mục hoặc chọn một thư mục",
    noBookmarksSelected: "Không có Bookmark nào được chọn",
    selectFolderError: "Vui lòng chọn một thư mục",
    errorUnexpected: "Đã xảy ra lỗi không mong muốn",
    restartExtension: "Vui lòng thử lại hoặc khởi động lại extension.",
    renamePlaceholder: "Nhập tên Bookmark mới",
    newFolderPlaceholder: "Nhập tên thư mục",
    selectFolder: "Chọn Thư mục",
    exportTitle: "Xuất Bookmarks",
    advancedSettings: "Cài đặt Nâng cao (HTML & CSV)",
    includeCreationDates: "Bao gồm ngày tạo",
    includeFolderModDates: "Bao gồm ngày chỉnh sửa thư mục",
    popupSubtitle: "Chọn định dạng xuất và cài đặt bạn muốn",
    exportFormat: "Định dạng Xuất",
    jsonDescription: "Định dạng đọc bằng máy (backup và khôi phục với import)",
    htmlDescription: "Trang web tương tác",
    csvDescription: "Dữ liệu bảng (dễ dàng mở trong Excel/Sheets)",
    netscapeDescription: "Định dạng trình duyệt tiêu chuẩn",
    includeCreationDatesDescription: "Thêm dấu thời gian tạo",
    includeFolderModDatesDescription: "Thêm dấu thời gian thư mục",
    exporting: "Đang xuất...",
    bookmarksTitle: "Bộ Sưu Tập Bookmarks Của Tôi",
    bookmarksHeader: "Bookmarks Của Tôi",
    exportedOn: "Đã in vào ngày",
    loadingBookmarks: "Đang tải bookmarks...",
    generatedBy: "Được tạo bởi Zero Bookmark Manager Extension",
    bookmarks: "bookmark",
    folders: "thư mục",
    created: "Đã tạo",
    modified: "Đã chỉnh sửa",
    unnamedFolder: "Thư mục không tên",
    notAvailable: "N/A",
    scrollToTop: "Scroll to Top",
    aiTitle: "Cấu hình AI Chatbot",
    favourite: "Yêu thích",
    removeFavourite: "Bỏ yêu thích",
    favoriteSuccess: "Đã thêm bookmark vào yêu thích!",
    unfavoriteSuccess: "Đã xóa bookmark khỏi yêu thích!",
    helpGuideTitle: "Hướng Dẫn",
    exportChatHistory: "Xuất Lịch Sử Chat",
    maximizeMinimize: "Phóng To/Thu Nhỏ",
    editAIConfig: "Chỉnh Sửa Cấu Hình AI",
    closeChat: "Đóng Chat",
    chatToggle: "Mở Chat",
    noChatHistory: "Không có lịch sử chat",
    loadingChat: "Đang xử lý...",
    moveBookmarkSuccess: "Đã chuyển bookmark thành công",
    moveBookmarkError: "Không tìm thấy bookmark hoặc thư mục không hợp lệ",
    searchFolderResult: "Các thư mục tìm thấy",
    noFoldersFound: "Không tìm thấy thư mục cho",
    aiBookmarkResponse: "Phản hồi AI",
    notSupported:
      "Xin lỗi, tôi chỉ có thể giúp với các tác vụ liên quan đến bookmark hoặc các câu hỏi đơn giản như giờ hoặc ngày.",
    youHave: "Bạn có",
    hereAreYourBookmarks: "Đây là danh sách bookmark của bạn",
    hereAreYourFolders: "Đây là danh sách thư mục của bạn",
    hereAreBookmarksInFolder: "Đây là danh sách bookmark trong thư mục",
    noBookmarksInFolder: "Không có bookmark trong thư mục này",
    addedBookmarkToFolder: "Tôi đã thêm bookmark",
    toFolder: "vào thư mục",
    updatedBookmark: "Tôi đã cập nhật bookmark",
    inFolder: "trong",
    deletedBookmark: "Tôi đã xóa bookmark",
    foundBookmarks: "Tôi tìm thấy",
    bookmarksMatching: "bookmark khớp với",
    noBookmarksFoundFor: "Tôi không tìm thấy bookmark nào khớp với",
    foundFolders: "Tôi tìm thấy các thư mục sau",
    noFoldersFoundFor: "Tôi không tìm thấy thư mục nào khớp với",
    movedBookmark: "Tôi đã chuyển bookmark",
    noFolders: "Bạn chưa có thư mục nào.",
    createdFolder: "Tôi đã tạo thư mục",
    renamedFolder: "Tôi đã đổi tên thư mục",
    to: "thành",
    alreadyExists: "đã tồn tại.",
    andAllItsContents: "và tất cả nội dung của nó",
    deletedFolder: "Tôi đã xóa thư mục",
    deleteFolderCancelled: "Hủy xóa thư mục",
    viewChanged: "Chế độ xem đã thay đổi thành",
    invalidView: "Chế độ xem không hợp lệ",
    themeChanged: "Chủ đề đã thay đổi thành",
    invalidTheme: "Chủ đề không hợp lệ",
    sortChanged: "Thứ tự sắp xếp đã thay đổi thành",
    invalidSort: "Kiểu sắp xếp không hợp lệ",
    checkingLinks:
      "Đã bắt đầu kiểm tra các liên kết hỏng. Kết quả sẽ hiển thị trên giao diện.",
    helpCommands: `
      <h4>Danh sach lenh</h4>
      <ul>
        <li><strong>/help</strong> - Xem danh sach lenh</li>
        <li><strong>dem bookmark</strong> - Dem bookmark</li>
        <li><strong>dem thu muc</strong> - Dem thu muc</li>
        <li><strong>liet ke bookmark</strong> - Liet ke tat ca bookmark</li>
        <li><strong>liet ke thu muc</strong> - Liet ke tat ca thu muc</li>
        <li><strong>liet ke bookmark trong thu muc "Work"</strong></li>
        <li><strong>dung @Work de chon thu muc</strong></li>
        <li><strong>them https://example.com vao thu muc "Work"</strong></li>
        <li><strong>chuyen bookmark "Tieu de" sang thu muc "Work"</strong></li>
        <li><strong>sua bookmark "Tieu de"</strong></li>
        <li><strong>xoa bookmark "Tieu de"</strong></li>
        <li><strong>tao thu muc "Work"</strong></li>
        <li><strong>doi ten thu muc "Cu" thanh "Moi"</strong></li>
        <li><strong>xoa thu muc "Work"</strong></li>
        <li><strong>tim bookmark "tu khoa"</strong></li>
        <li><strong>tim thu muc "tu khoa"</strong></li>
        <li><strong>yeu thich bookmark "Tieu de"</strong></li>
        <li><strong>doi che do xem card</strong></li>
        <li><strong>doi chu de dark</strong></li>
        <li><strong>sap xep a-z</strong></li>
        <li><strong>kiem tra link</strong></li>
      </ul>
    `,
    helpGuide: `
        <h4>Hướng Dẫn:</h4>
          <ol>
            <li><strong>/help</strong><br>
              - Xem danh sach lenh.
            </li>
            <li><strong>Dem:</strong><br>
              - <code>"dem bookmark"</code>, <code>"dem thu muc"</code>.
            </li>
            <li><strong>Liet ke:</strong><br>
              - <code>"liet ke bookmark"</code>, <code>"liet ke thu muc"</code>.<br>
              - <code>"liet ke bookmark trong thu muc \"Work\""</code>.<br>
              - Dung <code>@Work</code> de chon thu muc.
            </li>
            <li><strong>Them Bookmark:</strong><br>
              - <code>"them https://example.com vao thu muc \"Work\""</code>.
            </li>
            <li><strong>Chuyen Bookmark:</strong><br>
              - <code>"chuyen bookmark \"Tieu de\" sang thu muc \"Work\""</code> hoac <code>"chuyen bookmark id 123 sang thu muc \"Work\""</code>.
            </li>
            <li><strong>Sua Bookmark:</strong><br>
              - <code>"sua bookmark \"Tieu de\""</code> hoac <code>"sua bookmark id 123"</code>.
            </li>
            <li><strong>Xoa Bookmark:</strong><br>
              - <code>"xoa bookmark \"Tieu de\""</code> hoac <code>"xoa bookmark id 123"</code>.
            </li>
            <li><strong>Thu muc:</strong><br>
              - <code>"tao thu muc \"Work\""</code>, <code>"doi ten thu muc \"Cu\" thanh \"Moi\""</code>, <code>"xoa thu muc \"Work\""</code>.
            </li>
            <li><strong>Tim kiem:</strong><br>
              - <code>"tim bookmark \"tu khoa\""</code>, <code>"tim thu muc \"tu khoa\""</code>.
            </li>
            <li><strong>Yeu thich:</strong><br>
              - <code>"yeu thich bookmark \"Tieu de\""</code>.
            </li>
            <li><strong>Che do xem / Chu de / Sap xep:</strong><br>
              - <code>"doi che do xem card"</code>, <code>"doi chu de dark"</code>, <code>"sap xep a-z"</code>.
            </li>
            <li><strong>Kiem tra lien ket:</strong><br>
              - <code>"kiem tra link"</code>.
            </li>
            <li><strong>Luu y:</strong><br>
              - Che do local chi ho tro lenh bookmark.
            </li>
          </ol>
        `,
    clarifyBookmark:
      "Tui tìm thấy nhiều bookmark tên '{title}'. Bạn muốn chỉnh sửa cái nào? Hãy cung cấp URL hoặc thư mục.",
    noBookmarks: "Tui không tìm thấy bookmark nào có {0}.",
    updatedBookmark: "Tui đã cập nhật bookmark",
    inFolder: "trong",
    naturalLanguagePrompt:
      "Tui không biết. Thử lệnh như 'xóa bookmark ID 123' hoặc 'đổi tên bookmark ID 456 thành NewTitle'.",
    markedFavorite: "Tui đã đánh dấu bookmark",
    unmarkedFavorite: "Tui đã bỏ đánh dấu yêu thích cho bookmark",
    showBookmarkIds: "Hiển thị ID Bookmark",
    hideBookmarkIds: "Ẩn ID Bookmark",
    localStorageSettingsTitle: "Cài đặt Bộ nhớ tại web",
    saveSearchQuery: "Lưu Truy vấn Tìm kiếm",
    saveSelectedFolderId: "Lưu Thư mục Đã chọn",
    saveSortType: "Lưu Kiểu Sắp xếp",
    saveViewMode: "Lưu Chế độ Xem",
    saveCollapsedFolders: "Lưu Thư mục Thu gọn",
    saveCheckboxesVisible: "Lưu Hiển thị Hộp kiểm",
    allTags: "Tất cả Thẻ",
    viewDetail: "Xem Chi tiết",
    manageTags: "Quản lý Thẻ",
    selectTag: "Chọn Thẻ",
    tagExists: "Thẻ đã tồn tại",
    tagLimitError: "Không thể thêm quá 10 thẻ cho mỗi bookmark",
    saveSelectedTag: "Lưu Thẻ Đã chọn",
    addTag: "Thêm Thẻ",
    newTagPlaceholder: "Nhập tên thẻ...",
    currentTagsLabel: "Các thẻ hiện tại:",
    addNewTagLabel: "Thêm thẻ mới:",
    tagBgColorLabel: "Nền",
    tagTextColorLabel: "Chữ",
    addFromExistingLabel: "Hoặc thêm từ các thẻ đã có:",
    doneLabel: "Xong",
    tagLimitReached: "Đã đạt giới hạn thẻ",
    detailDateAdded: "Ngày Thêm",
    detailFolder: "Thư mục",
    includeFolderPath: "Bao gồm Đường dẫn Thư mục (cho CSV)",
    includeFolderPathDescription: "Thêm đường dẫn đầy đủ của thư mục (cho CSV)",
    includeIconData: "Bao gồm dữ liệu icon (Base64)",
    includeIconDataDescription: "Thêm favicon cho từng bookmark",
    exportOnlySelected: "Chỉ xuất các bookmark đã chọn",
    exportOnlySelectedDescription:
      "Nếu có bookmark được tick trong danh sách chính, chỉ xuất những bookmark đó",
    pinSuccess: "Đã ghim bookmark!",
    unpinSuccess: "Đã bỏ ghim bookmark!",
    pinToTop: "Ghim lên Đầu",
    unpin: "Bỏ ghim khỏi Đầu",
    errorCannotMoveFolderToSelf: "Không thể di chuyển thư mục vào chính nó.",
    errorCannotMoveFolderToDescendant:
      "Không thể di chuyển thư mục vào thư mục con của nó.",
    organizeFolders: "Sắp xếp Thư mục",
    organizeFoldersTitle: "Sắp xếp Thư mục",
    moveToFolderTitle: "Di chuyển Thư mục",
    moveFolderSuccess: "Đã di chuyển thư mục thành công!",
    filtersTitle: "Bộ lọc",
    searchTitle: "Tìm kiếm",
    folderActionsTitle: "Thao tác thư mục",
    selectionTitle: "Lựa chọn",
    healthSortAll: "Tất cả",
    healthSortDead: "Liên kết hỏng",
    healthSortSuspicious: "Liên kết đáng ngờ",
    healthSortSafe: "Liên kết an toàn",
    generateQrCode: "Tạo mã QR",
    noDuplicatesFound: "Không tìm thấy bookmark trùng lặp.",
    duplicatesRemoved: "bookmark trùng lặp đã được xóa.",
    checkLinks: "Kiểm tra liên kết",
    checkDuplicates: "Kiểm tra trùng lặp",
    bookmarkActionsTitle: "Thao tác Bookmark",
    appSettingsTitle: "Cài đặt ứng dụng",
    extensionOptionsTitle: "Tùy chọn tiện ích",
    bookmarkHealthTitle: "Kiểm tra Bookmark",
    bookmarkHealthSmallTitle: "Kiểm tra Bookmark",
    quickOpenTitle: "Hành động Mở Nhanh",
    quickOpenPopup: "Popup mặc định",
    quickOpenSidePanel: "Mở panel mặc định",
    quickOpenWeb: "Mở web mặc định",
    // Sidebar translations
    sidebarAllBookmarks: "Tất cả Bookmarks",
    sidebarFavorites: "Yêu thích",
    sidebarUnsorted: "Chưa phân loại",
    sidebarRecentlyAdded: "Thêm gần đây",
    sidebarFolders: "Thư mục",
    sidebarTags: "Thẻ",
    sidebarSort: "Sắp xếp",
    sidebarManage: "Quản lý",
    sidebarMoreFolders: "thư mục khác",
    sidebarBookmarks: "bookmarks",
  },
}

// ==========================================
// FUZZY SEARCH FUNCTIONS
// ==========================================

/**
 * Calculate Levenshtein distance between two strings
 * @param {string} a - First string
 * @param {string} b - Second string
 * @returns {number} - Edit distance
 */
function levenshteinDistance(a, b) {
  const matrix = []

  if (a.length === 0) return b.length
  if (b.length === 0) return a.length

  for (let i = 0; i <= b.length; i++) {
    matrix[i] = [i]
  }

  for (let j = 0; j <= a.length; j++) {
    matrix[0][j] = j
  }

  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b.charAt(i - 1) === a.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1]
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1, // substitution
          matrix[i][j - 1] + 1, // insertion
          matrix[i - 1][j] + 1, // deletion
        )
      }
    }
  }

  return matrix[b.length][a.length]
}

/**
 * Check if query characters appear in order within text (subsequence match)
 * @param {string} text - Text to search in
 * @param {string} query - Query string
 * @returns {object} - { matches: boolean, score: number, positions: number[] }
 */
function subsequenceMatch(text, query) {
  const textLower = text.toLowerCase()
  const queryLower = query.toLowerCase()
  const positions = []
  let queryIndex = 0
  let consecutiveBonus = 0
  let lastMatchIndex = -2

  for (let i = 0; i < textLower.length && queryIndex < queryLower.length; i++) {
    if (textLower[i] === queryLower[queryIndex]) {
      positions.push(i)
      // Bonus for consecutive matches
      if (i === lastMatchIndex + 1) {
        consecutiveBonus += 0.1
      }
      // Bonus for matching at word boundaries
      if (i === 0 || /[\s\-_./]/.test(text[i - 1])) {
        consecutiveBonus += 0.15
      }
      lastMatchIndex = i
      queryIndex++
    }
  }

  const matches = queryIndex === queryLower.length
  const baseScore = matches ? queryLower.length / textLower.length : 0
  const score = Math.min(1, baseScore + consecutiveBonus)

  return { matches, score, positions }
}

/**
 * Calculate match score between text and query using multiple algorithms
 * @param {string} text - Text to search in
 * @param {string} query - Query string
 * @returns {number} - Score from 0 to 1 (higher is better match)
 */
export function calculateMatchScore(text, query) {
  if (!text || !query) return 0

  const textLower = text.toLowerCase().trim()
  const queryLower = query.toLowerCase().trim()

  // Empty query matches everything
  if (!queryLower) return 1

  // Exact match - highest score
  if (textLower === queryLower) return 1

  // Contains exact query - very high score
  if (textLower.includes(queryLower)) {
    // Bonus if starts with query
    if (textLower.startsWith(queryLower)) return 0.95
    // Bonus if query appears at word boundary
    const wordBoundaryRegex = new RegExp(
      `(^|[\\s\\-_./])${escapeRegex(queryLower)}`,
      "i",
    )
    if (wordBoundaryRegex.test(text)) return 0.9
    return 0.85
  }

  // Check word-by-word match (for multi-word queries)
  const queryWords = queryLower.split(/\s+/).filter((w) => w.length > 0)
  const textWords = textLower.split(/\s+/).filter((w) => w.length > 0)

  if (queryWords.length > 1) {
    let matchedWords = 0
    for (const qWord of queryWords) {
      if (
        textWords.some(
          (tWord) => tWord.includes(qWord) || qWord.includes(tWord),
        )
      ) {
        matchedWords++
      }
    }
    const wordMatchScore = matchedWords / queryWords.length
    if (wordMatchScore >= 0.5) {
      return 0.7 * wordMatchScore
    }
  }

  // Subsequence match (characters in order)
  const subseqResult = subsequenceMatch(text, query)
  if (subseqResult.matches) {
    return Math.max(0.5, Math.min(0.8, subseqResult.score + 0.3))
  }

  // Levenshtein distance for typo tolerance
  const maxLen = Math.max(textLower.length, queryLower.length)
  const distance = levenshteinDistance(textLower, queryLower)
  const similarity = 1 - distance / maxLen

  // Only consider if similarity is reasonable
  if (similarity > 0.6) {
    return similarity * 0.6
  }

  // Check if any word in text starts with query
  for (const word of textWords) {
    if (word.startsWith(queryLower)) {
      return 0.7
    }
  }

  // Partial match - at least some characters match at start
  let prefixMatch = 0
  for (let i = 0; i < Math.min(queryLower.length, textLower.length); i++) {
    if (queryLower[i] === textLower[i]) {
      prefixMatch++
    } else {
      break
    }
  }
  if (prefixMatch >= 2 && prefixMatch >= queryLower.length * 0.5) {
    return 0.4 + (prefixMatch / queryLower.length) * 0.2
  }

  return 0
}

/**
 * Escape special regex characters
 */
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

/**
 * Fuzzy match search - returns true if text matches query with given threshold
 * @param {string} text - Text to search in
 * @param {string} query - Query string
 * @param {number} threshold - Minimum score threshold (0-1), default 0.5
 * @returns {boolean} - True if match score exceeds threshold
 */
export function fuzzyMatchSearch(text, query, threshold = 0.5) {
  const score = calculateMatchScore(text, query)
  return score >= threshold
}

/**
 * Highlight matched parts in text
 * @param {string} text - Original text
 * @param {string} query - Query to highlight
 * @returns {string} - HTML string with <mark> tags around matches
 */
export function highlightMatches(text, query) {
  if (!query || !text) return text

  const textLower = text.toLowerCase()
  const queryLower = query.toLowerCase()

  // Try exact substring first
  const exactIndex = textLower.indexOf(queryLower)
  if (exactIndex !== -1) {
    return (
      text.slice(0, exactIndex) +
      "<mark>" +
      text.slice(exactIndex, exactIndex + query.length) +
      "</mark>" +
      text.slice(exactIndex + query.length)
    )
  }

  // Subsequence highlighting
  const subseq = subsequenceMatch(text, query)
  if (subseq.matches && subseq.positions.length > 0) {
    let result = ""
    let lastIndex = 0
    for (const pos of subseq.positions) {
      result += text.slice(lastIndex, pos)
      result += "<mark>" + text[pos] + "</mark>"
      lastIndex = pos + 1
    }
    result += text.slice(lastIndex)
    return result
  }

  return text
}

export function safeChromeBookmarksCall(method, args, callback) {
  try {
    if (!chrome || !chrome.bookmarks || !chrome.bookmarks[method]) {
      console.error(`chrome.bookmarks.${method} is not available`)
      const language = localStorage.getItem("appLanguage") || "en"
      showCustomPopup(translations[language].errorUnexpected, "error", false)
      callback(null)
      return
    }
    chrome.bookmarks[method](...args, (result) => {
      if (chrome.runtime.lastError) {
        console.error(`Error in ${method}:`, chrome.runtime.lastError.message)
        const language = localStorage.getItem("appLanguage") || "en"
        showCustomPopup(translations[language].errorUnexpected, "error", false)
        callback(null)
        return
      }
      callback(result)
    })
  } catch (error) {
    console.error(`Unexpected error in ${method}:`, error)
    const language = localStorage.getItem("appLanguage") || "en"
    showCustomPopup(translations[language].errorUnexpected, "error", false)
    callback(null)
  }
}

export function debounce(func, wait) {
  let timeout
  return function (...args) {
    clearTimeout(timeout)
    timeout = setTimeout(() => func.apply(this, args), wait)
  }
}

export function showCustomPopup(
  message,
  type = "success",
  autoClose = true,
  onConfirm = null,
  showCancel = false,
) {
  const popup = document.getElementById("custom-popup")
  const title = document.getElementById("custom-popup-title")
  const messageEl = document.getElementById("custom-popup-message")
  const okButton = document.getElementById("custom-popup-ok")
  const cancelButton = document.getElementById("custom-popup-cancel")
  const language = localStorage.getItem("appLanguage") || "en"

  if (!popup || !title || !messageEl || !okButton) {
    console.error("Custom popup elements missing", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
      cancelButton: !!cancelButton,
    })
    return
  }

  try {
    // Thiết lập tiêu đề theo loại popup
    if (type === "loading") {
      title.textContent = language === "vi" ? "Đang xử lý..." : "Loading..."
    } else if (type === "success") {
      title.textContent = translations[language].successTitle
    } else if (type === "error") {
      title.textContent = translations[language].errorTitle
    } else {
      // info, warning, ...
      title.textContent = language === "vi" ? "Thông báo" : "Notification"
    }

    messageEl.textContent = message
    popup.classList.remove("hidden")

    // Áp dụng class theo type để có thể style khác nhau (success, error, loading, warning,...)
    popup.classList.remove("success", "error", "loading", "warning", "info")
    if (type) {
      popup.classList.add(type)
    }

    const currentTheme =
      document.documentElement.getAttribute("data-theme") || "light"

    // Remove all possible theme classes
    const allThemes = ["light", "dark", "dracula", "onedark"]
    allThemes.forEach((theme) => {
      popup.classList.remove(`${theme}-theme`)
    })

    // Apply current theme to popup
    popup.classList.add(`${currentTheme}-theme`)

    const closePopup = () => {
      popup.classList.add("hidden")
      document.removeEventListener("keydown", handleKeydown)
    }

    okButton.onclick = () => {
      closePopup()
      if (onConfirm) onConfirm()
    }

    if (cancelButton) {
      if (showCancel) {
        cancelButton.classList.remove("hidden")
        cancelButton.onclick = () => closePopup()
      } else {
        cancelButton.classList.add("hidden")
      }
    }

    popup.onclick = (e) => {
      if (e.target === popup) {
        closePopup()
      }
    }

    const handleKeydown = (e) => {
      if (e.key === "Enter") {
        okButton.click()
      } else if (e.key === "Escape") {
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)

    if ((type === "success" || type === "info") && autoClose && !onConfirm) {
      setTimeout(closePopup, 5000)
    }
  } catch (error) {
    console.error("Error in showCustomPopup:", error)
  }
}

export function showCustomConfirm(message, onConfirm, onCancel) {
  const popup = document.getElementById("custom-popup")
  const title = document.getElementById("custom-popup-title")
  const messageEl = document.getElementById("custom-popup-message")
  const okButton = document.getElementById("custom-popup-ok")
  const language = localStorage.getItem("appLanguage") || "en"
  const buttonsContainer = popup?.querySelector(".rename-popup-buttons")

  if (!popup || !title || !messageEl || !okButton || !buttonsContainer) {
    console.error("Custom confirm popup elements missing", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
      buttonsContainer: !!buttonsContainer,
    })
    return
  }

  try {
    title.textContent = translations[language].confirmTitle || "Confirm"

    messageEl.textContent = message

    popup.classList.remove("hidden")

    const cancelButton = document.createElement("button")
    cancelButton.className = "button cancel"
    cancelButton.textContent = translations[language].cancel || "Cancel"

    buttonsContainer.appendChild(cancelButton)

    const isDarkMode = document.body.classList.contains("dark-theme")
    popup.classList.toggle("light-theme", !isDarkMode)
    popup.classList.toggle("dark-theme", isDarkMode)

    const closePopup = () => {
      popup.classList.add("hidden")
      if (buttonsContainer.contains(cancelButton)) {
        buttonsContainer.removeChild(cancelButton)
      }
      document.removeEventListener("keydown", handleKeydown)
    }

    okButton.onclick = () => {
      onConfirm()
      closePopup()
    }

    cancelButton.onclick = () => {
      if (onCancel) onCancel()
      closePopup()
    }

    popup.onclick = (e) => {
      if (e.target === popup) {
        if (onCancel) onCancel()
        closePopup()
      }
    }

    const handleKeydown = (e) => {
      if (e.key === "Enter") {
        onConfirm()
        closePopup()
      } else if (e.key === "Escape") {
        if (onCancel) onCancel()
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)
  } catch (error) {
    console.error("Error in showCustomConfirm:", error)
  }
}

export function showCustomGuide() {
  // Ensure DOM is loaded
  if (!document.getElementById("custom-guide")) {
    console.error(
      "Custom guide popup not found. Waiting for DOMContentLoaded...",
    )
    document.addEventListener("DOMContentLoaded", showCustomGuide)
    return
  }

  const popup = document.getElementById("custom-guide")
  const title = document.getElementById("custom-guide-title")
  const messageEl = document.getElementById("custom-guide-message")
  const okButton = document.getElementById("custom-guide-ok")
  const language = localStorage.getItem("appLanguage") || "en"

  // Log missing elements for debugging
  if (!popup || !title || !messageEl || !okButton) {
    console.error("Custom guide elements missing:", {
      popup: !!popup,
      title: !!title,
      messageEl: !!messageEl,
      okButton: !!okButton,
    })
    // Display a fallback error message
    if (document.getElementById("custom-popup")) {
      showCustomPopup(
        `${translations[language].errorTitle}: ${
          translations[language].errorUnexpected || "Unexpected error"
        }`,
        "error",
        true,
      )
    } else {
      alert("Error: Help guide cannot be displayed due to missing elements.")
    }
    return
  }

  try {
    title.textContent = translations[language].helpGuideTitle

    messageEl.innerHTML = translations[language].helpGuide

    popup.classList.remove("hidden")

    const isDarkMode = document.body.classList.contains("dark-theme")
    popup.classList.toggle("light-theme", !isDarkMode)
    popup.classList.toggle("dark-theme", isDarkMode)

    const closePopup = () => {
      popup.classList.add("hidden")
      document.removeEventListener("keydown", handleKeydown)
      document.removeEventListener("click", handleOutsideClick) // Thêm dòng này
    }

    okButton.onclick = () => closePopup()

    // Trong hàm showCustomGuide, thay thế phần event listener:
    const handleOutsideClick = (e) => {
      if (!popup.contains(e.target)) {
        closePopup()
      }
    }

    // Sử dụng click thay vì mousedown, và thêm một độ trễ nhỏ
    setTimeout(() => {
      document.addEventListener("click", handleOutsideClick)
    }, 100) // 100ms delay

    // Ngăn sự kiện click từ nội dung popup lan ra ngoài
    popup.addEventListener("click", (e) => {
      e.stopPropagation()
    })

    const handleKeydown = (e) => {
      if (e.key === "Enter" || e.key === "Escape") {
        closePopup()
      }
    }

    document.addEventListener("keydown", handleKeydown)
  } catch (error) {
    console.error("Error in showCustomGuide:", error)
    if (document.getElementById("custom-popup")) {
      showCustomPopup(
        `${translations[language].errorTitle}: ${
          translations[language].errorUnexpected || "Unexpected error"
        }`,
        "error",
        true,
      )
    } else {
      alert("Error: Help guide cannot be displayed.")
    }
  }
}

export function showLocalStorageSettingsPopup() {
  const popup = document.getElementById("localstorage-settings-popup")
  const title = document.getElementById("localstorage-settings-title")
  const saveButton = document.getElementById("localstorage-settings-save")
  const cancelButton = document.getElementById("localstorage-settings-cancel")
  const language = localStorage.getItem("appLanguage") || "en"

  if (!popup || !title || !saveButton || !cancelButton) {
    console.error("Local storage settings popup elements missing:", {
      popup: !!popup,
      title: !!title,
      saveButton: !!saveButton,
      cancelButton: !!cancelButton,
    })
    showCustomPopup(translations[language].errorUnexpected, "error", true)
    return
  }

  // Set multilingual labels
  title.textContent = translations[language].localStorageSettingsTitle
  saveButton.textContent = translations[language].save
  cancelButton.textContent = translations[language].cancel

  // Debug checkbox visibility
  const checkboxes = document.querySelectorAll(
    '.localstorage-settings-container input[type="checkbox"]',
  )

  popup.classList.remove("hidden")

  // Apply current theme
  const currentTheme =
    document.documentElement.getAttribute("data-theme") || "light"
  const allThemes = ["light", "dark", "dracula", "onedark"]
  allThemes.forEach((theme) => popup.classList.remove(`${theme}-theme`))
  popup.classList.add(`${currentTheme}-theme`)
}

export function hideLocalStorageSettingsPopup() {
  const popup = document.getElementById("localstorage-settings-popup")
  if (popup) {
    popup.classList.add("hidden")
  }
}
